# Generated by Django 2.1.3 on 2018-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='id',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='Title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
