# Generated by Django 2.1.3 on 2018-11-18 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20181118_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='DeadlineDate',
            new_name='Deadline_Date',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='CreatedAt',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
