# Generated by Django 2.1.3 on 2018-11-18 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0005_auto_20181118_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
